<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
    <PackageReference Include="xunit.v3.core" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Evoogle.Core\Evoogle.Core.csproj" />
  </ItemGroup>

</Project>
